# References:
- Ponomaroff, A., 2018. pandas.wide_to_long. [Online] 
Available at: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.wide_to_long.html
[Accessed 10 3 2019].

In [1]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
por = pd.read_csv("C:/Users/test/Desktop/data/student-por.csv",delimiter=';')
mat = pd.read_csv("C:/Users/test/Desktop/data/student-mat.csv",delimiter=';')
por['course'] = 'por'
mat['course'] = 'mat'

combined_data = pd.concat([por, mat], ignore_index=True)
cols = combined_data.columns.tolist()
cols = cols[-1:] + cols[:-1]
combined_data = combined_data[cols]
n_combined_data = pd.DataFrame(combined_data,copy=True)
n_combined_data["id"] = n_combined_data.index
cols = n_combined_data.columns.tolist()
cols = cols[-1:] + cols[:-1]
n_combined_data = n_combined_data[cols]

In [3]:
cat_vars= n_combined_data.select_dtypes(include=['object']).columns.to_list()
dummies_data = pd.DataFrame(n_combined_data,copy=True)
for var in cat_vars:
    cat_list='var'+'_'+var
    cat_list = pd.get_dummies(dummies_data[var], prefix=var, drop_first=True)
    data1=dummies_data.join(cat_list)
    dummies_data=data1
    
data_vars=dummies_data.columns.values.tolist()
to_keep=[i for i in data_vars if i not in cat_vars]

dummies_data_final=dummies_data[to_keep]

In [4]:
#(Ponomaroff, 2018)
long_data = pd.wide_to_long(dummies_data_final,stubnames='G',i=['id'],j='Grade')
long_data.sort_index(inplace=True)

In [5]:
long_data

            internet_yes  reason_home  Fjob_health  course_por  \
id   Grade
0    1                 0            0            0           1
     2                 0            0            0           1
     3                 0            0            0           1
1    1                 1            0            0           1
     2                 1            0            0           1
     3                 1            0            0           1
2    1                 1            0            0           1
     2                 1            0            0           1
     3                 1            0            0           1
3    1                 1            1            0           1
     2                 1            1            0           1
     3                 1            1            0           1
4    1                 0            1            0           1
     2                 0            1            0           1
     3                 0            1            0           1
5    1                 1            0            0           1
     2                 1            0            0           1
     3                 1            0            0           1
6    1                 1            1            0           1
     2                 1            1            0           1
     3                 1            1            0           1
7    1                 0            1            0           1
     2                 0            1            0           1
     3                 0            1            0           1
8    1                 1            1            0           1
     2                 1            1            0           1
     3                 1            1            0           1
9    1                 1            1            0           1
     2                 1            1            0           1
     3                 1            1            0           1
...                  ...          ...          ...         ...
1034 1                 0            0            0           0
     2                 0            0            0           0
     3                 0            0            0           0
1035 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0
1036 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0
1037 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0
1038 1                 0            0            0           0
     2                 0            0            0           0
     3                 0            0            0           0
1039 1                 0            0            0           0
     2                 0            0            0           0
     3                 0            0            0           0
1040 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0
1041 1                 0            0            0           0
     2                 0            0            0           0
     3                 0            0            0           0
1042 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0
1043 1                 1            0            0           0
     2                 1            0            0           0
     3                 1            0            0           0

            guardian_mother  Dalc  activities_yes  freetime  Fjob_services  \
id   Grade
0    1                    1     1               0         3              0
     2                    1     1               0         3              0
     3                    1     1               0         3              0
1    1                    0     1               0         3              0
     2                    0     1               0         3              0
     3                    0     1               0         3              0
2    1                    1     2               0         3              0
     2                    1     2               0         3              0
     3                    1     2               0         3              0
3    1                    1     1               1         2              1
     2                    1     1               1         2              1
     3                    1     1               1         2              1
4    1                    0     1               0         3              0
     2                    0     1               0         3              0
     3                    0     1               0         3              0
5    1                    1     1               1         4              0
     2                    1     1               1         4              0
     3                    1     1               1         4              0
6    1                    1     1               0         4              0
     2                    1     1               0         4              0
     3                    1     1               0         4              0
7    1                    1     1               0         1              0
     2                    1     1               0         1              0
     3                    1     1               0         1              0
8    1                    1     1               0         2              0
     2                    1     1               0         2              0
     3                    1     1               0         2              0
9    1                    1     1               1         5              0
     2                    1     1               1         5              0
     3                    1     1               1         5              0
...                     ...   ...             ...       ...            ...
1034 1                    1     1               0         3              0
     2                    1     1               0         3              0
     3                    1     1               0         3              0
1035 1                    1     2               1         4              0
     2                    1     2               1         4              0
     3                    1     2               1         4              0
1036 1                    1     1               1         4              0
     2                    1     1               1         4              0
     3                    1     1               1         4              0
1037 1                    1     1               0         3              1
     2                    1     1               0         3              1
     3                    1     1               0         3              1
1038 1                    1     1               1         1              0
     2                    1     1               1         1              0
     3                    1     1               1         1              0
1039 1                    0     4               0         5              1
     2                    0     4               0         5              1
     3                    0     4               0         5              1
1040 1                    1     3               0         4              1
     2                    1     3               0         4              1
     3                    1     3               0         4              1
1041 1                    0     3               0         5              0
     2                    0     3               0         5              0
     3                    0     3               0         5              0
1042 1                    1     3               0         4              0
     2                    1     3               0         4              0
     3                    1     3               0         4              0
1043 1                    0     3               0         2              0
     2                    0     3               0         2              0
     3                    0     3               0         2              0

            failures  ...  paid_yes  Mjob_other  sex_M  reason_reputation  \
id   Grade            ...
0    1             0  ...         0           0      0                  0
     2             0  ...         0           0      0                  0
     3             0  ...         0           0      0                  0
1    1             0  ...         0           0      0                  0
     2             0  ...         0           0      0                  0
     3             0  ...         0           0      0                  0
2    1             0  ...         0           0      0                  0
     2             0  ...         0           0      0                  0
     3             0  ...         0           0      0                  0
3    1             0  ...         0           0      0                  0
     2             0  ...         0           0      0                  0
     3             0  ...         0           0      0                  0
4    1             0  ...         0           1      0                  0
     2             0  ...         0           1      0                  0
     3             0  ...         0           1      0                  0
5    1             0  ...         0           0      1                  1
     2             0  ...         0           0      1                  1
     3             0  ...         0           0      1                  1
6    1             0  ...         0           1      1                  0
     2             0  ...         0           1      1                  0
     3             0  ...         0           1      1                  0
7    1             0  ...         0           1      0                  0
     2             0  ...         0           1      0                  0
     3             0  ...         0           1      0                  0
8    1             0  ...         0           0      1                  0
     2             0  ...         0           0      1                  0
     3             0  ...         0           0      1                  0
9    1             0  ...         0           1      1                  0
     2             0  ...         0           1      1                  0
     3             0  ...         0           1      1                  0
...              ...  ...       ...         ...    ...                ...
1034 1             0  ...         1           0      0                  0
     2             0  ...         1           0      0                  0
     3             0  ...         1           0      0                  0
1035 1             0  ...         1           0      0                  1
     2             0  ...         1           0      0                  1
     3             0  ...         1           0      0                  1
1036 1             1  ...         0           0      0                  0
     2             1  ...         0           0      0                  0
     3             1  ...         0           0      0                  0
1037 1             0  ...         1           0      0                  0
     2             0  ...         1           0      0                  0
     3             0  ...         1           0      0                  0
1038 1             1  ...         0           1      0                  0
     2             1  ...         0           1      0                  0
     3             1  ...         0           1      0                  0
1039 1             2  ...         1           0      1                  0
     2             2  ...         1           0      1                  0
     3             2  ...         1           0      1                  0
1040 1             0  ...         0           0      1                  0
     2             0  ...         0           0      1                  0
     3             0  ...         0           0      1                  0
1041 1             3  ...         0           1      1                  0
     2             3  ...         0           1      1                  0
     3             3  ...         0           1      1                  0
1042 1             0  ...         0           0      1                  0
     2             0  ...         0           0      1                  0
     3             0  ...         0           0      1                  0
1043 1             0  ...         0           1      1                  0
     2             0  ...         0           1      1                  0
     3             0  ...         0           1      1                  0

            higher_yes  schoolsup_yes  reason_other  Fedu  absences   G
id   Grade
0    1               1              1             0     4         4   0
     2               1              1             0     4         4  11
     3               1              1             0     4         4  11
1    1               1              0             0     1         2   9
     2               1              0             0     1         2  11
     3               1              0             0     1         2  11
2    1               1              1             1     1         6  12
     2               1              1             1     1         6  13
     3               1              1             1     1         6  12
3    1               1              0             0     2         0  14
     2               1              0             0     2         0  14
     3               1              0             0     2         0  14
4    1               1              0             0     3         0  11
     2               1              0             0     3         0  13
     3               1              0             0     3         0  13
5    1               1              0             0     3         6  12
     2               1              0             0     3         6  12
     3               1              0             0     3         6  13
6    1               1              0             0     2         0  13
     2               1              0             0     2         0  12
     3               1              0             0     2         0  13
7    1               1              1             0     4         2  10
     2               1              1             0     4         2  13
     3               1              1             0     4         2  13
8    1               1              0             0     2         0  15
     2               1              0             0     2         0  16
     3               1              0             0     2         0  17
9    1               1              0             0     4         0  12
     2               1              0             0     4         0  12
     3               1              0             0     4         0  13
...                ...            ...           ...   ...       ...  ..
1034 1               1              0             1     2         2  10
     2               1              0             1     2         2   9
     3               1              0             1     2         2  10
1035 1               1              0             0     4         7   6
     2               1              0             0     4         7   5
     3               1              0             0     4         7   6
1036 1               1              0             0     3         0   7
     2               1              0             0     3         0   5
     3               1              0             0     3         0   0
1037 1               1              0             0     1         0   7
     2               1              0             0     1         0   9
     3               1              0             0     1         0   8
1038 1               1              0             0     1         0   6
     2               1              0             0     1         0   5
     3               1              0             0     1         0   0
1039 1               1              0             0     2        11   9
     2               1              0             0     2        11   9
     3               1              0             0     2        11   9
1040 1               1              0             0     1         3  14
     2               1              0             0     1         3  16
     3               1              0             0     1         3  16
1041 1               1              0             0     1         3  10
     2               1              0             0     1         3   8
     3               1              0             0     1         3   7
1042 1               1              0             0     2         0  11
     2               1              0             0     2         0  12
     3               1              0             0     2         0  10
1043 1               1              0             0     1         5   8
     2               1              0             0     1         5   9
     3               1              0             0     1         5   9

[3132 rows x 41 columns]

In [6]:
long_data = pd.DataFrame(long_data.to_records())

In [7]:
long_data.head(10)

,id,Grade,internet_yes,reason_home,Fjob_health,course_por,guardian_mother,Dalc,activities_yes,freetime,...,paid_yes,Mjob_other,sex_M,reason_reputation,higher_yes,schoolsup_yes,reason_other,Fedu,absences,G
0,0,1,0,0,0,1,1,1,0,3,...,0,0,0,0,1,1,0,4,4,0
1,0,2,0,0,0,1,1,1,0,3,...,0,0,0,0,1,1,0,4,4,11
2,0,3,0,0,0,1,1,1,0,3,...,0,0,0,0,1,1,0,4,4,11
3,1,1,1,0,0,1,0,1,0,3,...,0,0,0,0,1,0,0,1,2,9
4,1,2,1,0,0,1,0,1,0,3,...,0,0,0,0,1,0,0,1,2,11
5,1,3,1,0,0,1,0,1,0,3,...,0,0,0,0,1,0,0,1,2,11
6,2,1,1,0,0,1,1,2,0,3,...,0,0,0,0,1,1,1,1,6,12
7,2,2,1,0,0,1,1,2,0,3,...,0,0,0,0,1,1,1,1,6,13
8,2,3,1,0,0,1,1,2,0,3,...,0,0,0,0,1,1,1,1,6,12
9,3,1,1,1,0,1,1,1,1,2,...,0,0,0,0,1,0,0,2,0,14

In [9]:
long_data.to_csv("C:/Users/test/Desktop/data/combined8.csv")